name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Configure Python
      run: |
        python3 -m pip install ivpm
        python3 -m ivpm update
        ./packages/python/bin/python3 -m pip install wheel twine
        ./packages/python/bin/python3 -m pip install setuptools --upgrade
        export BUILD_NUM=$GITHUB_RUN_ID
        ./packages/python/bin/python3 setup.py bdist_wheel --universal
    - name: Run Tests
      run: |
        export PYTHONPATH=`pwd`/src:`pwd`/tests
        cd tests
        ../packages/python/bin/python3 -m pytest 
        

#    - name: Build docs
#      run: |
#        ./packages/python/bin/sphinx-build -M html ./doc/source build
#        touch build/html/.nojekyll
    - name: Publish to PyPi
      if: startsWith(github.ref, 'refs/heads/master')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
#    - name: Publish Docs
#      if: startsWith(github.ref, 'refs/heads/master')
#      uses: JamesIves/github-pages-deploy-action@4.1.7
#      with:
#        branch: gh-pages
#        folder: build/html

